language: go

services:
  - docker

go:
  - 1.14

before_script:
  - make setup

script:
  - make lint
  - make unit-tests
  - make integration-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)